#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.example.demo.model
  mapperLocations: classpath:mapping/*.xml


---

#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://180.153.59.145/xdd_comquality
    username: educ
    password: xdd@818
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource